### ISSUE TITLE
úkol-09: Základní dotazy - Teplota ve městech

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#10]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-09_Zakladni_Dotazy-Teplota_ve_mestech.ipynb

Ahoj Anet,

odevzádávám úkol č. 9 i s bonusy. Jen bych ráda věděla a potřebuji poradit, jak vypíšu všechny řádky z dotazu (který má např. 127 řádků). Standardně se vypíše jen prvních a posledních 5 řádků.

Děkuji,
Lenka

**Comment by AnetaPopelova** [comment]
👍  ukol super, tady mas medaily za bonusy a zkouseni ruznych variant reseni🥇
---

---

**K limitu radku:**
Muzes menit parametry toho, jak se `pandas` (nebo `jupyter`) chova.

Takhle zmenis chovani pandas obecne pro cely script:
```
pandas.set_option("display.max_rows", None, "display.max_columns", None)
```

Tohle jen pro to jedno konkretni volani:
```
with pandas.option_context('display.max_rows', None, 'display.max_columns', None):  
    print(temperature)
```

Bude to fungovat v terminalu, kdyz pouzijes `.py` soubor. 

Pro `Jupyter` dostanes hlasku: _Output exceeds the size limit. Open the full output data in a text editor_ 
Kliknutim na _limit_ muzes upravit, kolik radek bude vracet (porad potrebujes mit spravne nastaven i ten `pandas`. 
Kliknutim na _text editor_ otevres cely dataframe v novem okne. 

Vice moznovati nastaveni najdes v dokumentaci: https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

**Comment by zitkovalenka** [comment]
:-D děkuji za medaily ;-) A na ten limit se podívám.
