### ISSUE TITLE
úkol-10: Agregace a spojování: Zaměstnanci a projekty

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#11]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-10_Agregace_Spojovani-Zamci_a_projekty.ipynb

Odevzdávám úkol č. 10 i s bonusy.

Mám jen jednu otázku. Chtěla jsem u níže uvedeného spojení dvou dataframe vypsat jen některé sloupce (4 sloupce z df "zamci" a 2 sloupce z df "vykazy" a vůbec mi to nefungovalo právě s výpisem konkrétních sloupců. Bez určení, které sloupce vypsat, mi vše funguje v pořádku.

Výpis sloupců, nefunkční:
`zamci_hod_vykazy = pandas.merge(zamci[["jmeno","prijmeni","cislo_zamestnance", "mesto"]], vykazy[["hours","project"]], left_on = "cislo_zamestnance", right_on = "employee_id") `

Jen spojení 2 dataframe bez výpisu sloupců, funkční:
`zamci_hod_vykazy = pandas.merge(zamci, vykazy, left_on = "cislo_zamestnance", right_on = "employee_id")`

V čem je problém? Děkuji :-)

**Comment by AnetaPopelova** [comment]
Kdyz vybiras jen nejake sloupce, musis **vzdy vybrat ty, pres ktere to spojujes** (a jakekoliv dalsi k tomu).

`zamci_hod_vykazy = pandas.merge(zamci[["jmeno","prijimeni","cislo_zamestnance", "mesto"]], vykazy[["hours","project", "employee_id"]], left_on = "cislo_zamestnance", right_on = "employee_id") `

**Comment by zitkovalenka** [comment]
Děkuji, zkusila jsem a už to funguje ;-)

Ještě mám jeden dotaz. V první části Výkazy jsem si nevěděla úplně rady, jak vyfiltrovat ty osoby, které již nejsou zaměstnanci (které pak mám uložit do csv souboru). Nebyla jsem schopna použít `NaN` hodnotu přímo pro filtr. Tak jsem to obešla přes vytvoření nového sloupce `je_zamec`, který obsahuje hodnoty `Ano` nebo `Ne`. A ty jsem již vyfiltrovat dokázala.

`nezamci = platy_zamci.query("je_zamec == 'Ne'")`

Je i jiná možnost, aniž bych musela vytvářet pomocný sloupec?
Na to navazuje, že bych ráda vymazala sloupec `je_zamec?`, protože jsem pak s ním nemohla pracovat (kvůli otazníku). Proto jsem vytvořila sloupec, který ten otazník neobsahuje.

Poradila bys mi prosím, jak tento sloupec `je_zamec?` vymazat? V lekci jsme to nebrali a teď by se mi to hodilo :-)
Děkuji.

**Comment by AnetaPopelova** [comment]
Jak se zbavit sloupcu (nebo i radek, kdyz na to prijde): `df.drop(columns=['B', 'C'])`
Dokumentace: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

Odfiltrovani NaN hodnot - postupovala bych takto:

1. vytvorim podminku `platy_zamci["plat"].isna()` - vraci hodnoty true/false
2. pouziju ji na dataframe `platy_zamci[platy_zamci["plat"].isna()]`
3. vytvorim novy dataframe `nezamci = platy_zamci[platy_zamci["plat"].isna()]`

Dej vedet, jestli je to to, co hledas.

**Comment by zitkovalenka** [comment]
Děkuji. To znamená, že bod číslo 2 "použiji podmínku na dataframe" vyfiltruje jen True hodnoty? Podmínka totiž vypíše True i False. Prostě vše. Na tom jsem právě zamrzla, že jsem potřebovala vidět vyfiltrované jen True hodnoty a "== True" nefungovalo.

**Comment by AnetaPopelova** [comment]
Ano, je to jako u podmínek. Když tě budu citovat:

`Praha = temperature[temperature["City"].isin(["Prague"])]`

To taky vrátí `true` a rovnou to ty `true` hodnoty vybere.
