### ISSUE TITLE
úkol-11: Regulární výrazy: Pošta

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#12]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-11_Regularni_vyrazy-Posta.ipynb

Ahoj Aneto,

prosím o radu:

1. při ukládání souboru na disk (import request...):
    Musela jsem stáhnutí html souboru obejít tím, že jsem si ho vytvořila přes poznámkový blok 

2. s regulárním výrazem v úplně posledním bodu, kdy potřebuji najít PSČ i s celým názvem města, včetně čísla pošty (např. Liberec 15). Jestli to chápu dobře, nemá se vypsat jen Liberec, ale Liberec 15?

    Tak, jak mám nyní regulární výraz vytvořený, tak zachycuje jen názvy měst, pokud obsahuje jen písmena a navíc mám výpis u některých měst včetně dalšího textu za názvem města. Ve snaze regulární výraz upravit přesněji, jsem vždy neuspěla (viz zkoušky v kódu).

Děkuji za radu.

**Comment by zitkovalenka** [comment]
První bod je vyřešen. Prosím o radu s doladěním regulárního výrazu. Je mi jasné, že `\D ?*` využije celou sekvenci znaků, takže není divu, že v některých případech mi to vypíše více než potřebuji. Zkouším všechno možné, ale zatím jsem nedospěla ke 100% výsledku.

**Comment by AnetaPopelova** [comment]
K regularnimu vyrazu - zkus se podivat bliz na kvantifikatory :-) 

Pro jmeno mesta potrebujes najit:
- velka nebo mala _pismena_ nebo _mezery_, ktere se musi vyskytnout minimalne 1x, maximalne neomezeno (bude se hodit `[]` a `+` - ani ` \w` neni k zahozeni). 
- pak muze rovnou navazovat nekolik cislic (minimalne 0x, maximalne neomezeno)


P.S.: Bacha, ve for-cyklu na konci mas stejne pojmenove obe promenne. 
```
for psc_adresy in psc_adresy: 
    print(psc_adresy)
```

**Comment by zitkovalenka** [comment]
Děkuji, upraveno. Nakonec jsem použila a funguje:
`regularni_vyraz_psc_adresa = re.compile(r"\d{3} \d{2} \w* ?\w* ?\w* ?\w*")`

Zkoušela jsem i přes níže uvedené, ale bohužel nevím proč, mi to nic nevypíše, přitom si myslím, že by mělo vypsat PSČ s názvem pošty, kde jsou jen písmena. Ano, stále by to nevypsalo číslo pošty (např. Liberec 15), postupně bych dodala. Ale nefunguje ani to, co si myslím, že by fungovat mělo.

`regularni_vyraz_psc_adresa = re.compile(r"\d{3} \d{2} [À-ž]{1,} ?[À-ž]{0,} ?[À-ž]{0,} ?")`

**Comment by AnetaPopelova** [comment]
1. super, jen to opakovani ` \w* ?\w* ?\w* ?\w*`by slo jeste zjednodusit treba na `[\w ]+\d*`

2. pozor [**À**-ž] neni jen rozsirene [A-z], jsou to uplne jine znaky (viz tabulka dole v [zadani](https://github.com/andywaltlova/python-1-podzim-2022/blob/master/ukoly/ukol-11.md))
--> zkus **À** vymenit za **A** nebo to zapsat nejak takhle `[a-zA-ZÀ-ž ]`
