### ISSUE TITLE
úkol-12: Vizualizace

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#13]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-12_Vizualizace.ipynb

Odevzdávám úkol č. 12. Ačkoliv mám úkol dle mého názoru hotov, narazila jsem na pár nejasností, které budu ráda, když  mi objasníš :-) 

1. histogram - ráda bych věděla, jak vytvořit název pro osu X. Nebo název pro všechny tři grafy. (Např. "Platy v Kč", "Platy ve městech").  Název jsem zkoušela přes `plt.title("Callcentrum hovory v sekundách\n\n", fontweight ="bold")`, ale neuspěla jsem. Název osy X jsem nikde v dokumentaci nenašla, jak přidat.

2. histogram - nelze mi uložit graf jako obrázek. Je potřeba to napsat jinak? Zkoušela jsem:
`plt.savefig('ukol-12_platy.png')`  - uloží se prázdný obrázek
a také uložit předchozí krok do nějaké proměnné a pak `platy_zamci.plt.savefig('ukol-12_platy.png')` nebo platy_mesta. Nefunguje. Stejný problém mám také u teploty ve městech.

3. teplota ve městech - u kroku při vytváření grafu jsem si vymyslela argumenty a neštěstí to funguje. Nicméně v dokumentaci jsem žádné "column" ani "by" nenašla... 
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.boxplot.html

4. nejsou teploty v Helsinkách ve stupních Celsia, kdežto v Miami Beach nebo Tokyu ve Farenheitech?

Mockrát děkuji,
Lenka

**Comment by AnetaPopelova** [comment]
1. Nemyslim, ze je to mozne (alespon ja to taky nenasla). 

V momente, kdy chces definovat vice vlastnosti a obzvlast u vice-grafu, sahla bych po moznosti s vytvorenim objektu `fig, ax`. 

> Explanation: Labels are properties of axes objects, that needs to be set on each of them. [LINK](https://stackoverflow.com/questions/42832675/setting-axis-labels-for-histogram-pandas)


Tady je to hezky krok po kroku [vysvetlene](https://mode.com/example-gallery/python_histogram/). 
Ty "jednoduche" metody maji sve limity. 

---

2. `plt.savefig('soubor.jpg')` je treba volat pred `plt.show()`.

> Explanation: plt.show() clears the whole thing, so anything afterwards will happen on a new empty. [LINK](https://stackoverflow.com/a/47343051/13318363)

---

3. Tady ti bude stacit aplikovat na dataframe `.groupby("City")`, pak pouzit `.boxplot` a muze se hodit i `subplots=False`. 

Muzes to vyuzit i jako prilezitost na seznameni se s knihovnou `seaborn` - je to takova "nadstavba" `matplotlib`u, ktera umoznuje dalsi kreativnejsi praci a upravy grafu. 

```
import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(data=vybrana_mesta, 
            x='City', 
            y='AvgTemperature',
            )

plt.show()
```

4. Vsechno je to ve Fahrenheitech, viz [puvodni cviceni](https://github.com/andywaltlova/python-1-podzim-2022/blob/master/ukoly/ukol-09.md). Myslim, ze v Helsinkach v listopadu bude kolem 0 °C.

**Comment by zitkovalenka** [comment]
Kód upraven.

ad 1. Prosím ještě o opravu - použila jsem: 
```
fig, ax = plt.subplots()    # jednotka 15 a 7 je v palcích
print(type(fig))
print(type(ax))

ax.set_title("Platy v Kč", fontweight="bold", fontsize = 24) 
```
a místo toho, aby byl název v grafu, tak je mimo graf. Jinými slovy existují 2 grafy, jeden původní se 3 městy a druhý prázdný, jen s osou X a Y a názvem.

To se mi už stalo dříve, když jsem to zkoušela... Poradíš, co mám špatně? 

ad 2. Děkuji ;-) 

ad 3. pokusila jsem se, graf se mi objevil podle mě správný, ale např. část kódu:
```
temp_3_city_grouped = temp_3_city.groupby("City")["AvgTemperature"]   # (vypíše něco, jen když dám .sum(), apod.)
temp_3_city_grouped
```
neudělá jakoby nic. Resp. něco udělá, ale nelze to vypsat. Objeví se:
`<pandas.core.groupby.generic.SeriesGroupBy object at 0x000001AFC3718550>`

To asi není správně...?

Graf jsem následně vytvořila tímto a zdá se, že ok:
```
import seaborn as sns

sns.boxplot(data= temp_3_city, # vybrana_mesta, 
            x='City', 
            y='AvgTemperature',
            )

plt.show()
```

ad 4. vše jasné :-)

**Comment by AnetaPopelova** [comment]
Prazdne je to, protoze tam sice vytvoris "ramecek", ale uz to nenakrmis daty. 

Ta logika je zhruba takova:
```
import pandas
import matplotlib.pyplot as plt

# Vytvoris si prostor, kam budes sazet pod-grafy
fig, axes = plt.subplots(nrows=1, ncols=3)
fig.subplots_adjust(hspace=0.5)
fig.suptitle('Platy v Kč')
fig.set_size_inches(15, 5)

# Vytvoris si jednotlive grafy
for ax, (mesto, subdf) in zip(axes.flatten(), platy_zamci.groupby('mesto')):
    subdf.hist('plat', ax=ax, bins = 6, color="pink")
    ax.set_title(mesto)
    ax.set_xlabel(f"Value in {mesto}")
    ax.set_ylabel("Frequency")

plt.show()
```

3. Tu divnou hlasku casto to vraci, kdyz zapomenes zavolat funkci...
Za `temp_3_city.groupby("City")["AvgTemperature"] ` patri jeste napr. `.mean()`. Groupby volane nad konkretnim sloupcem/sloupci potrebuje vedet, co s daty udelat (secist, zpumerovat atd.)


Ty ale budes spis potrebovat:
```
grouped = temp_3_city[["City", "AvgTemperature"]].groupby("City")
grouped.boxplot(figsize=(13,5), subplots=False)
```
