### ISSUE TITLE
Úkol-02: Slovníky_cykly - Státy světa

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#2]
https://github.com/zitkovalenka/Python1-Czechitas/commit/1d8ed4e18266cac1a920631b47dbb08976bcb1ab

Nemohu přesně vymyslet, aby mi program psal "Neznámý region", ačkoliv to mám v programu zakomponované, vyplní se prázdné pole. Zkoušela jsem dva způsoby (oba dva jsou v kódu ponechány - přes get a také pomocí elif). Ani jeden podle mě nefunguje správně, ale netuším, jak jinak bych to měla napsat.

V bonusové části, kdy se snažím získat sumu obyvatel za subregion. Zde také poprosím o radu. Znám sumu regionu vypsanou jednou částkou, ale nevím, jak se mám dostat o řád větší detail a to tak, že se zeptám na obecnější (region), ale vypsat se má větší detail (subregion). Moc děkuji.

**Comment by AnetaPopelova** [comment]
a) za mne je nejelantnejsi reseni problemu `"Neznamy region"` ukladat si zeme z regionu do `listu` a pak zkontrolovat, jestli je/neni prazdny. `.get `a podobne srandy muzes vynechat. 

b) potrebujes se zeptat nejprve na region (to tam mas), nekam si ulozit informace, ktere potrebujes (subregion, populace) a pak vytvorit slovnik a pak do nej pridavat zaznamy pro kazdy subregion. Hint: `dictionary['key'] = value` a `=+`

**Comment by zitkovalenka** [comment]
Poslala jsem nový kód a k němu dala docela dlouhý komentář. Jen nevím, kam to zmizlo. Vidíš to? Děkuji

**Comment by zitkovalenka** [comment]
a) pro zkoušení jsem si vytvořila novou řádek do seznamu s regionem Atrapa a zemí (name) "". Abych mohla testovat neznámý region. Jestli to chápu správně, tak se může stát, že region má jen jeden stát, který je prázdný a v tomto případě je potřeba vypsat "Neznámý region". Chápu to dobře?

Vytvořený slovník jen ze států regionu, který mě zajímá mám vytvořen (snad dobře?) a jen mi nefunguje ten "neznámý region". Vůbec nevím, jak označit/ najít prázdný stát. Bude to "" nebo snad s mezerou" "? Předpokládám "" bez mezery ve sloupci name.
Zkoušela jsem nalézt prázdný stát jako jediný ve vybraném regionu právě pomocí "" nebo " " a nebo také False či True. Ale nepomohlo ani jedno. Také jsem přemýšlela, že bych vytvořila 2 sloupce v seznamu a to název státu a právě proměnnou False či True, jako vyplněnost. Ale opět jsem narazila na stejné, že vlastně nevím, jak ho mám nalézt. Zkoušela jsem i None a nic.

b) ponechala jsem součet počtu obyvatel regionu jako mustr. Hned níže se pokouším o stejné pro subregion. Ale nedokáži doplnit prázdný seznam o 1 klíč (název subregionu) a 1 hodnotu (hodnotu populace). Zkoušela jsem to různě a také neúspěšně.

Moc děkuji za pomoc.

**Comment by zitkovalenka** [comment]
Jinak na GitHubu by nový kód měl být, protože v Changes není vůbec mezi změnami. Je tedy někde nahraný a nemůžu ho tedy nahrát znovu. Ale přitom jsem ho tu viděla, ale již  nevidím. Ty nový kód vidíš? Klidně ti ho pošlu mailem nebo nevím, jak jinak :-D.

**Comment by zitkovalenka** [comment]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-02_Slovniky_cykly-Staty_sveta.py

Tak jsem ten kód asi našla. Ale původní komentář stejně nevidím. Ale více méně jsem to zde popsala znovu.

**Comment by zitkovalenka** [comment]
V GitHub tedy musím znovu okopírovat ten odkaz nového kódu a vložit ho sem do toho stejného Issue, abys ho viděla? Myslela jsem si, že to bude automatické, když se jedná o stejný soubor z VSC se stejným názvem, jen jsem ho znovu nahrála na GitHub. Ale zdá se mi, že se v "Code" objevil nový kód a ten asi sem musím zkopírovat. Chápu to dobře? Nebo se to dá udělat nějak líp, aby se to provázalo automaticky? Jsem překvapená, že to automaticky nefunguje - stejný  název, stejný soubor, jen nahrané znovu. Děkuji :-) . A omlouvám se za zmatky, tohle v postupu vůbec není popsáno :-D . A nové issue jsem zadávat nechtěla.

**Comment by AnetaPopelova** [comment]
Chces si zavolat? Stejne tu u toho sedim a snazim se to sepsat.

**Comment by zitkovalenka** [comment]
Můžeme, mám chvílí. Jen malý už na mě čeká vedle ;-) 724716618. Nebo nevím, jestli se to dá i jinak.

**Comment by AnetaPopelova** [comment]
Pripoj se na nas obvykly zoom meeting.

**Comment by zitkovalenka** [comment]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-02_Slovniky_cykly-Staty_sveta.py

**Comment by zitkovalenka** [comment]
První část zcela hotova. Ohledně bonusového úkolu - podle mě se nejedná o správný výsledek. Výsledkem nemělo být jen jedno číslo (v mém případě je), ale seznam subregionů a součtů jejich obyvatel. Jak ukazuje příklad.

Například pokud uživatel zadá Europe, tak by měl být výsledek následující:

{'Northern Europe': 104628222, 'Southern Europe': 152182570, 'Western Europe': 194539965, 'Eastern Europe': 295337425}

Neměla bych nakonec přeci jen vytvářet seznam a přidávat záznamy nějak pomocí "append"? Jen nevím jak, zvládla bych buď jen klíč nebo jen hodnotu, ale obojí teď nevím jak.

**Comment by AnetaPopelova** [comment]
Staci male kouzlo na poslednim radku: Chces zobrazit CELY slovnik.

Misto `print(f"Počet obyvatel subregionů je {subregionSlovnik[subregion]}.")` chces tohle:

`print(f"Počet obyvatel subregionů je {subregionSlovnik}.")
`

Jinak 👍

**Comment by zitkovalenka** [comment]
Ahááá. Celý slovník... Je pravda, že jsem tam měla jen jeden detail... Děkuji, to mě uniklo. :-)
