### ISSUE TITLE
Úkol-03: Funkce - SMS brána

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#3]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-03_Funkce-SMS_br%C3%A1na.py

**Comment by zitkovalenka** [comment]
Ahoj Aneto,

odevzdávám úkol, nicméně bych potřebovala pomoci s tím, že jsem omylem (nevím ani jak) poslala na github všechny kódy, co jsem měla v VSC a samozřejmě je tam vůbec nechci. Postupně jsem je vymazala, ale povedlo se mi zasáhnout také do Úkolu č.2.  Níže vidíš, co vidím v záložce "Code".

![image](https://user-images.githubusercontent.com/114017674/194712098-09716df7-9b1c-4150-8c6b-a1c2570a4f9e.png)

Když  kliknu na název "Úkol-02", tak se mi zdá, že kód je ok, ale když kliknu na "Odevzdávám 3.úkol", tak se mi tam objeví docela dost změn, viz screen níže. To stejné vidím samozřejmě také u úkolu č.3, když kliknu na text "odevzdávám 3. úkol". Když kliknu do názvu "Úkol-03", tak vidím taky správný kód.

![image](https://user-images.githubusercontent.com/114017674/194712180-d24a17a0-154b-4fc1-9d80-d5e8b92096b3.png)
 
Jak to mám vrátit zpět? Abych viděla prostě jen ten poslední kód?

Mockrát děkuji :-)

**Comment by AnetaPopelova** [comment]
Muzeme to zkusit probrat zitra zive? Klidne pred lekci nebo po ni... Jak se vyznat v tech verzich na githubu budu ukazovat, valci s tim vic holek. Prozatim bud v klidu, mas to tam vsechno spravne 👍 

No a k tomu ukolu:

- mas funkci ve funkci, coz neni zadouci - mely by to byt 2 samostatne funkce (jedna na cisla, jedna na text), ktere potom postupne zavolas v ramci nejakeho programu (ve kterem se ptas na ty vstupy).
- kontrola predvolby nema kontrolovat, do ktere zeme SMS posilas, ale jen overit, jestli tam predvolba je. 
   - pokud tam je, cislo smi mit 13 znaku
   - pokud tam neni, cislo smi mit jen 9 znaku

Zkus prosim rozdelit reseni na dve funkce a kraty program, ktery je bude pouzivat.

**Comment by zitkovalenka** [comment]
Za mě spíš po lekci, v lekci tu mám ještě půl hoďky dítko. Spíš bude záležet, v kolik se kdo vlastně přihlásí, většinou je to na poslední chvíli.

Aha, to v zadání ale nebylo, že bych nemohla mít funkci vnořenou. Prostě se jedná o dvě funkce a funguje to přesně tak, jak má. Ze zadání jsem také nepochopila, že bych mohla mít 13 i 9 čísel, takže obojí může uživatel zadat. Právě i z komentáře na Slacku jsem pochopila, že vlastně má mít 13 čísel. Tak jsem to ošetřila hned na vstupu u uživatele, aby nedošlo k mýlce.

Ze začátku jsem také uvažovala o tom, že by to byly dvě funkce oddělené, ale nešlo mi použít např. parametr False (že něco zadal špatně, tak nepokračuj ve výzvě na zadání textu zprávy) mimo tu danou funkci. Jen v jejím těle. Nelze tedy toto False použít mimo funkci, tedy před druhou funkcí pomocí if. Ve smyslu - zadal jsi číslo správně, tak můžeš pokračovat v zadávání zprávy. To se dělá tedy jak?

**Comment by AnetaPopelova** [comment]
Dulezite je, ze to dela to, co po nem chces ty  ;-)

K tomu cislu je na Slacku [tohle](https://python1podzim2022.slack.com/archives/C045GFWRKCZ/p1664987517994099), coz tedy potvrzuje moji teorii - ale diky za podnet k presneni zadani...

---

K rozdeleni funkci: Ten parametrer napr. False by nebyl soucasti dalsi funkce. 

V podstate mas jednu funkci, ktera pouze kontroluje cislo a vrati True nebo False.
Pak druhou funkci, ktere pouze pocita cenu. 

A pak samotny script, ktery tyhle funkce pouzije:

- zepta se na cislo
- pouzije funkci na kontrolu
- pokud je cislo spravne, zepta se na text
- pouzije  funkci na vypocet ceny

Predstav si, ze mas spoustu funkci a programu... a pak potrebujes zkontrolovat cislo nejen pro SMS, ale treba pri zadavani kontaktu v e-ehopu (to je trochu divoke, ale nic lepsiho me  nenapada, uf). Muzes pak svou funkci znovu pouzit i v jinem programu. Urcite existuji pripady, [kdy se hodi vnorena funkce](https://realpython.com/inner-functions-what-are-they-good-for/), ale vetsinou chces mit funkce co nejvice jednoucelove. Jeden ukon, jedna funkce.

**Comment by zitkovalenka** [comment]
Změnila jsem kód na 2 nezávislé funkce a snažím se je volat níže. První část volání (True) si myslím, že mi funguje dobře, ale v případě False bych očekávala, že mě to nepustí k zadání textu zprávy, ale neděje se tak. Snažím se toto řešit pomocí "break", aby se kód shodil, ale evidentně to mám špatně nebo nevím, jak na to.

Taky se mi zdá neučesaná hlavička funkcí. Musím je mít nad vlastní definicí, jinak proměnné neexistují a nemůže je funkce použít, proto je musím mít vždy nad tou vlastní definicí funkce. Např. bych čekala, že mohu zadat vlastní vstup na číslo a zprávu až za definicí funkcí, tedy těsně před if podmínku. Ale nelze to takhle udělat.

Dá se to udělat jinak? Nebo to mám v pořádku? Učili jsme se sice funkci zavolat, ale už ne dál s ní pracovat, což se zdá, že pořádně neumím, nevím, jak na to.

**Comment by AnetaPopelova** [comment]
Hezky, uz jsi skoro u cile 👍 Jen to jeste trochu zprehazime.

V programu budes mit (skoro) vzdycky:
- nejdriv importy (`import math`)
- definice vsech funkci
- program samotny, ktery si vola ruzne funkce a pouziva ruzne importy

Tim uz mas napul vyhrano.

Ted funkce samotna - nejdriv vstup: 

Pro `overeni` je vstupem jen telefonni cislo. Nedava smysl mit informaci o spravnosti (`bool`) jako vstup - to az vystup.
A ten mas spravne, funkce vraci `return platneCislo`

Pri volani funkce je treba si tu vracenou hodnotu napr. ulozit do promenne. 
`je_cislo_platne = overeni(phoneNo)`

A pak se muzes ptat `if je_cislo_platne == True` atd.
Nebo si to zkratit a mit `if overeni(phoneNo) == True`. 

To je vse! Spravne poradi kusu kodu a prace s vysledkem volani. 

Dej mi vedet, jestli je to jasnejsi. Mozna po dnesni lekci trid to bude zase davat o neco vetsi smysl...

**Comment by zitkovalenka** [comment]
Kód upraven na dvě nezávislé funkce, učesán a změnila jsem také názvy na snake_case.

**Comment by AnetaPopelova** [comment]
Boží! 


P.S.: Doufám, že jsi to nedělala "protože jsem to řekla", ale spíš protože ti ti dává smysl…?

**Comment by zitkovalenka** [comment]
Ještě ve funkcích trochu tápu, takže když tvořím novou, tak se projistotu dívám na "vzor", resp. si ho kontroluji.
Co se týče přepracování do OOP, tak ho chápu a smysl mi rozhodně dává. A jsem ráda, že sis na mě udělala čas a pomohla jsi mi s učesáním, zjistila jsem tak, že mi to pak funguje, když zavolám funkci až úplně "vespod" a mezi tím si klidně mohu klidně zadávat konstanty.
Na snake_case si budu muset zvyknout, mě více vyhovuje camelCase. Ale je zbytečné si něco zafixovat, pokud se to skutečně používá jinak.

**Comment by AnetaPopelova** [comment]
Na ten snake_case (a zapis kodu obecne) existuje dokonce [norma PEP 8](https://peps.python.org/pep-0008/#function-and-variable-names) ;-)
