### ISSUE TITLE
Úkol-04: Třídy: Kuchařka

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#4]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-04_Tridy-Kucharka.py

Posílám první hotovou část (část s recepty, jeho měny apod.). Prosím o shlédnutí, jestli je alespoň v první části vše ok. Mě vše fungovalo, jak jsem si představovala :-) . 

S druhou částí (Kuchařka), bych potřebovala poradit. Vytvořila jsem objekt, který je hned v __init__ seznamem (doufám, že jsem to vytvořila správně). Nebo jsem na špatné cestě?

Jestli jsem to pochopila správně, tak když chci přidat položku, tak se to má zapsat do seznamu a přičíst 1 k počtu receptů. I funkci s počtem receptů jsem zadala, ale patrně ne správně, protože se buď nezvyšuje (je stále 0) nebo mi to háže chybu. 

Jinými slovy prosím také o shlédnutí vytvoření Kuchařky (seznam) a o radu při přidávání receptů a počtu receptů. 
Mají se recepty přidávat již při vytváření receptů v první části nebo je to zcela nezávislé a naopak recepty do Kuchařky přidávám až samostatně voláním funkcí pro přidání dalšího receptu do Kuchařky?

Mockrát děkuji za radu. 

Jinak s VSC stále bojuji, teď nejsem schopna na GitHub nahrát vůbec nic a nevím kam se mi poděla většina programů. Nevím jak, se vymazaly... :-((( . Psala jsem i na Slack a díky tomu jsem byla schopna nahrát program alespoň ručně.

**Comment by zitkovalenka** [comment]
Tak od pátku čekám na reakci a až teď jsem si uvědomila, že jsem tě nepřidala do issue.... Tak snad se brzy ozveš. Děkuji, Lenka

**Comment by AnetaPopelova** [comment]
Nevim, jestli te to utesi - ale ja k tem ukolum stejne sedla az dneska.

`Recepty` jsou fajn 👍 

`Kucharka`

V  `__str__` chybi zavorky u `self.pocet_receptu`. 

Ja jsem na to pocitani receptu pouzila funkci `len` , zavolanou nad tim slovnikem...
Ale to, co tam mas, bude fungovat taky. *

Jen je treba spravit `pridej_recept` a pouzit tam `append` pro pridani polozky do seznamu `recepty`. 
A bacha na ta velka pismena - ty maji jen tridy, ale ty tady vkladas promennou.

*protoze iterujes nejdriv na prazdnym slovnikem, po prvim pridani to ukaze 0. Po druhem pridani 1 atd.

**Comment by AnetaPopelova** [comment]
Jo a ten GitHub spravime, neboj. Jen se prosim prihlas pred/po/behem lekce.

**Comment by zitkovalenka** [comment]
Odevzdávám úkol bez bonusu. Na bonus se ještě podívám, ale chci mít vnitřně odfajfknuto, že úkol je hotov :-) . Navíc taky trochu, aby mi "někde" nezmizel.

**Comment by zitkovalenka** [comment]
Přidávám ještě tento kód, kterým se snažím vyřešit bonus. Bohužel se pořád motám v tom, že neumím použít výsledek z první funkce do druhé funkce a nejde mi to ani v těle programu.

Jestli jsem to pochopila správně, tak pomocí funkce zkusit, která je definovaná v 1.  kroku (recept), mám pak být schopná tento recept uložit i s jeho náležitostmi do seznamu, který je definován ve funkci v Kuchařce. Rozumím tomu správně? Jinými slovy, ty recepty, kterým volám funkci z receptu "zkusit", tak se mají uložit do seznamu a vypsat se se všemi náležitostmi receptu. Zkoušela jsem různými způsoby a jeden z nich je kód níže. Bohužel bez úspěchu. Jdu aleposň správnou cestou?

# BONUS 
class Recept:
    def __init__(self, nazev, narocnost, url_adresa,vyzkouseno=False):
        self.nazev = nazev
        self.narocnost = narocnost
        self.url_adresa = url_adresa
        self.vyzkouseno = vyzkouseno

    def __str__(self):
        if self.vyzkouseno == True:
            return f"Recept {self.nazev} (náročnost {self.narocnost}) vyzkoušeno: {self.url_adresa}"
        else:
            return f"Recept {self.nazev} (náročnost {self.narocnost}) nevyzkoušeno: {self.url_adresa}"

    def zmen_narocnost(self, nova_narocnost):
        self.narocnost = nova_narocnost

    def zkusit(self):
        self.vyzkouseno = True
        return self.vyzkouseno
    
    """def vyzkousene_recepty(self):
        self.vyzkousene_recepty_prom = []
        if self.vyzkouseno == True:
            #self.vykousene_recepty_prom.append(recept)
            return f"{self.vyzkousene_recepty_prom()}"""

class Kucharka:
    def __init__(self, nazev, autor):
        self.nazev = nazev
        self.autor = autor
        self.recepty = []
        self.vyzkousene_recepty = []

    def __str__(self):
        return f"V kuchařce {self.nazev} od {self.autor} je {self.pocet_receptu()} receptů." 
    def pocet_receptu(self):
        self.pocet_receptu_prom = 0
        for i in self.recepty:
            self.pocet_receptu_prom = self.pocet_receptu_prom + 1
        return self.pocet_receptu_prom
    """def pocet_receptu(self):
        pocet_receptu = len(self.recepty)
        #print(f"V kucharce je {pocet_receptu} receptů.")  
        return pocet_receptu"""
    def pridej_recept(self, novy_recept):
        self.recepty.append(novy_recept)
    
    def vyzkousene_recepty(self, vyzkousene_recepty_prom):
        if self.vyzkouseno == True:
            self.recepty.append(vyzkousene_recepty_prom)
        #self.vyzkousene_recepty_prom = []
        #if self.vyzkousene_recepty_prom == True:
        #    self.vyzkousene_recepty_prom.append(recept)
        #    return f"{self.vyzkousene_recepty_prom()}

recept_1 = Recept("Štrůdl", 3, "https://www.nejrecept.cz/recept/fantasticky-stavnaty-jablecny-zavin-r5687")
recept_1.zmen_narocnost(5)
print(recept_1)
recept_2 = Recept("Bábovka", 2, "https://www.toprecepty.cz/recept/1673-hrnickova-babovka/")
print(recept_2)
# recept_2.zkusit()
# print(recept_2)  
recept_3 = Recept("Croissant", 5, "https://www.toprecepty.cz/recept/5541-croissanty/")
print(recept_3)

kucharka=Kucharka("Dobrůdky", "Lentilka")
print(kucharka)
kucharka.pocet_receptu()            # musím nejprve fci zavolat, abych mohla vypsat výsledek
#print(kucharka.pocet_receptu)
kucharka.pridej_recept(recept_1)    # musím nejprve fci zavolat, abych mohla vypsat výsledek
kucharka.pocet_receptu()            # musím nejprve fci zavolat, abych mohla vypsat výsledek
# print(kucharka.pocet_receptu())
print(kucharka)
kucharka.pridej_recept(recept_2) 
kucharka.pocet_receptu()     
print(kucharka)
kucharka.pridej_recept(recept_3) 
kucharka.pocet_receptu()     
print(kucharka)
"""
print(kucharka.vyzkousene_recepty())
recept_2.zkusit()
print(recept_2)  
print(kucharka.vyzkousene_recepty())
"""
recept_2.zkusit()
print(recept_2)
recept_3.zkusit()
print(recept_3)

if recept.vyzkouseno == True:
    print kucharka.vyzkousene_recepty

**Comment by zitkovalenka** [comment]
`# BONUS 
class Recept:
    def __init__(self, nazev, narocnost, url_adresa,vyzkouseno=False):
        self.nazev = nazev
        self.narocnost = narocnost
        self.url_adresa = url_adresa
        self.vyzkouseno = vyzkouseno

    def __str__(self):
        if self.vyzkouseno == True:
            return f"Recept {self.nazev} (náročnost {self.narocnost}) vyzkoušeno: {self.url_adresa}"
        else:
            return f"Recept {self.nazev} (náročnost {self.narocnost}) nevyzkoušeno: {self.url_adresa}"

    def zmen_narocnost(self, nova_narocnost):
        self.narocnost = nova_narocnost

    def zkusit(self):
        self.vyzkouseno = True
        return self.vyzkouseno
    
    """def vyzkousene_recepty(self):
        self.vyzkousene_recepty_prom = []
        if self.vyzkouseno == True:
            #self.vykousene_recepty_prom.append(recept)
            return f"{self.vyzkousene_recepty_prom()}"""

class Kucharka:
    def __init__(self, nazev, autor):
        self.nazev = nazev
        self.autor = autor
        self.recepty = []
        self.vyzkousene_recepty = []

    def __str__(self):
        return f"V kuchařce {self.nazev} od {self.autor} je {self.pocet_receptu()} receptů." 
    def pocet_receptu(self):
        self.pocet_receptu_prom = 0
        for i in self.recepty:
            self.pocet_receptu_prom = self.pocet_receptu_prom + 1
        return self.pocet_receptu_prom
    """def pocet_receptu(self):
        pocet_receptu = len(self.recepty)
        #print(f"V kucharce je {pocet_receptu} receptů.")  
        return pocet_receptu"""
    def pridej_recept(self, novy_recept):
        self.recepty.append(novy_recept)
    
    def vyzkousene_recepty(self, vyzkousene_recepty_prom):
        if self.vyzkouseno == True:
            self.recepty.append(vyzkousene_recepty_prom)
        #self.vyzkousene_recepty_prom = []
        #if self.vyzkousene_recepty_prom == True:
        #    self.vyzkousene_recepty_prom.append(recept)
        #    return f"{self.vyzkousene_recepty_prom()}

recept_1 = Recept("Štrůdl", 3, "https://www.nejrecept.cz/recept/fantasticky-stavnaty-jablecny-zavin-r5687")
recept_1.zmen_narocnost(5)
print(recept_1)
recept_2 = Recept("Bábovka", 2, "https://www.toprecepty.cz/recept/1673-hrnickova-babovka/")
print(recept_2)
# recept_2.zkusit()
# print(recept_2)  
recept_3 = Recept("Croissant", 5, "https://www.toprecepty.cz/recept/5541-croissanty/")
print(recept_3)

kucharka=Kucharka("Dobrůdky", "Lentilka")
print(kucharka)
kucharka.pocet_receptu()            # musím nejprve fci zavolat, abych mohla vypsat výsledek
#print(kucharka.pocet_receptu)
kucharka.pridej_recept(recept_1)    # musím nejprve fci zavolat, abych mohla vypsat výsledek
kucharka.pocet_receptu()            # musím nejprve fci zavolat, abych mohla vypsat výsledek
# print(kucharka.pocet_receptu())
print(kucharka)
kucharka.pridej_recept(recept_2) 
kucharka.pocet_receptu()     
print(kucharka)
kucharka.pridej_recept(recept_3) 
kucharka.pocet_receptu()     
print(kucharka)
"""
print(kucharka.vyzkousene_recepty())
recept_2.zkusit()
print(recept_2)  
print(kucharka.vyzkousene_recepty())
"""
recept_2.zkusit()
print(recept_2)
recept_3.zkusit()
print(recept_3)

if recept.vyzkouseno == True:
    print kucharka.vyzkousene_recepty`

**Comment by zitkovalenka** [comment]
zkoušela jsem jako "add code" a vypadá to úplně stejně špatně ten kód.... Tak ti to zkouším poslat ještě na Slack, třeba to bude lepší.

**Comment by zitkovalenka** [comment]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-04_Tridy-Kucharka-Bonus.py

Odevzdávám úkol č. 4 i s bonusem. Doladily jsme to společně s Andy.

**Comment by AnetaPopelova** [comment]
💯

**Comment by zitkovalenka** [comment]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-04_Tridy-Kucharka-Bonus_vc_List_Comprehension.py

Ahoj Aneto,

prosím mrkni se ještě na tento kód. Snažím se pro "vyzkousene_recepty" vytvořit list comprehension. Jedná se o identický kód jako uzavřený úkol č.4, jen měním vnitřek metody `vyzkousene_recepty(self)`  na list comprehension. Ale nemám to správně. 

Ve cvičeních na kódím je mi vše jasné a mám kódy správně, ale s tímto úkolem mi to nějak nejde. Mohla by ses na to prosím podívat? 

Mám tam co se má dít vepředu, pak za "if" podmínku a za podmínkou for cyklus. Ale nemám to správně. Chtěla bych totiž zkusit za úkol č. 5 dědičnost, tak si zkouším alespoň na tomto příkladu list comprehension.

Mockrát děkuji.

**Comment by AnetaPopelova** [comment]
To poradi je jine:

`[y for y in a if y not in b]`

Zdroj: https://stackoverflow.com/questions/15474933/list-comprehension-with-if-statement

**Comment by zitkovalenka** [comment]
Upraveno. Mrkni prosím. Tentokrát to funguje a podle mě správně :-)

**Comment by AnetaPopelova** [comment]
🥇
