### ISSUE TITLE
Úkol-05: Dědičnost

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#5]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/05_D%C4%9Bdi%C4%8Dnost/ukol-05_Dedicnost-Nemoc.py

Všechny soubory mám nově vždy ještě v jednom adresáři, tak se mi nahrály do GitHub taky trochu jinak (je i v GitHub vnořen do adresáře jako jediný soubor). Tak snad nebudeš mít problém kód vidět.

Snad mám vše správně. Chtěla bych jen poradit s tím, jestli jsem správně zadala__init__ metodu ve třídě Koronavirus. V zadání sice bylo, že se má převzít z Nemoci a pak níže se v zadání bylo uvedeno, že mám dát natvrdo např. 12 a počet obětí taky nějaký. 

Následně v příkladu v zadání se volala tato funkce jinak a to takto:

corona = Koronavirus('Coronavirus', ['omikron'])

Což jsem vůbec nepochopila, když omikron zadávám díky funkci pridej_variantu. Tak jsem si zadání přizpůsobila i částečně dle posledního textu v zadání, že mám zvolit fixně inkubační dobu např. 12, počet obětí 0 a šíření vzduchem. Což jsem nakonec zadala právě přímo do metodiy __init__.

A tedy pak vytvářím koronavirus jen tím, že vložím jeho jméno pomocí:
`corona = Koronavirus("Coronavirus")`

Nebo to mám změnit, že v __init__ to bude obecně a dám to natvrdlo až při vytváření toho koronaviru pomocí proměnné corona?

Děkuji :-)

**Comment by zitkovalenka** [comment]
Omlouvám se, zase jsem tě tam nepřidala...

**Comment by AnetaPopelova** [comment]
Koukni prosim do kanalu ukol-5 na Slacku, Andy nekolikrat upresnovala zadani. Snad to neco objasni. 

Treba to predavani inkubacni doby a spol je ted popsano takhle (a myslim, ze uz to dava smysl - a mas to spravne 👍 ).

> Hodnoty atributu inkubacni_doba, pocet_obeti a sireni budou v __init__ metode tridy Koronavirus predane __init__ metode materske tridy (pres super().__init__(...)).


---
Jinak k variantam, za me mas dve moznosti:
Bud tak jak to mas ty - varianty lze vkladat jen pres funkci. 

Nebo:
Zacit s jednou variantou pri vytvatreni a dalsi (delta atd.) pridavat pomoci metody. 

```
class Koronavirus(Nemoc):
    def __init__(self, jmeno, varianty):
        super().__init__(jmeno, inkubacni_doba=12, sireni="vzduchem", pocet_obeti=0)
        self.varianty = []
```

`corona = Koronavirus("Coronavirus", "omikron")`
