### ISSUE TITLE
Úkol-05: List Comprehension z kodim.cz

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#6]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/05_D%C4%9Bdi%C4%8Dnost/ukol-05_List_Comprehension-kodim.py

**Comment by zitkovalenka** [comment]
Odevzdávám také úkol na List Comprehension z Kódím.

**Comment by AnetaPopelova** [comment]
Hezky! 👍 

**Drobnosti**

Tady jsi mela slovnik - ma to byt seznam seznamu viz nize.
```
# Vytvořte seznam dvouprvkových seznamů obsahujících pouze polední a noční teplotu.
dvojice =[[str(teplota[1]) + "," + str(teplota[2])] for teplota in teploty]
print(dvojice)
```

U posledniho ukolu by jsi mohla udelat dva for cykly za sebou v jednom radku. No a na vypocet prumeru si napisu funkci, abych nemusela pocet zaznamu pocitat zvlast.

```
def prumer(seznam):
    return sum(seznam) / len(seznam)

prumerna_teplota = prumer([teplota for den in teploty for teplota in den])
```

**Comment by zitkovalenka** [comment]
Jo aha, teď se dívám, že jsem udělala celkovou teplotu, ne celkovou průměrnou teplotu. :-D Jsem se tak soustředila asi na tu sumu, že jsem zapomněla vypočítat průměr...
