### ISSUE TITLE
úkol-06: Čtení a zápis do souboru

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#7]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-06-Zapis_a_cteni_ze_souboru-Znamky.py

Aneto, odevzdávám úkol č. 6, zatím bez bonusu. Nicméně bych byla ráda, kdybys mi ukázala, jak dosáhnu stejného s použitím  radek[0] a pro kazdy radek v radky[1:].... Jak psala Andy. Zkoušela jsem to všelijak a vůbec mi to nešlo. Přitom by to mělo být to stejné... Například už if radky[0] nebo` if radky!=radky[0]` mi vůbec ten první řádek nevzalo. Vůbec nic se nestalo, bralo to pořád všechny řádky (to druhé` if radky!=radky[0]` )

Andy psala:
radky = nejaky list
zapisu radky[0] do souboru / ulozi msi do modifikovanych radku
pro kazdy radek v radky[1:] zapisu radek s replacnutymi hodnotami / ulozi msi h odo seznamu k zapsani

**Comment by zitkovalenka** [comment]
Například jsem zkoušela toto a nefuguje mi to. Napíše mi to do souboru jen 1. řádek a vůbec nezná znamky_replace. A nedokázala jsem ho přesvědčit ani přes elif, ani kdy jsem to nechala přímo v těle programu, ne v if podmínce. To mi napíše zase, že write musí mít argument string, ne list...

`with open("ukol-06-znamky_za_semestr.txt","r", encoding="utf-8") as vstup:
    radky = vstup.readlines()

if radky[0]:
    prvni_radek = radky[0]
for radek in radky[1:]:
    # radek = [radek.split() for radek in radky] 
    znamky_replace = [radek.replace("1","A").replace("2","B").replace("3","C").replace("4","D").replace("5","F") for radek in radky]


with open("ukol-06-znamky_za_semestr-opraveno.txt","w", encoding="utf-8") as vystup:
    vystup.write(prvni_radek)

with open("ukol-06-znamky_za_semestr-opraveno.txt","a", encoding="utf-8") as vystup:
    vystup.write(znamky_replace)`

**Comment by zitkovalenka** [comment]
Tak jsme to s Andy daly dohromady. Odevzdávám tedy hned dvě možnosti zápisu. Nějak mě nenapadlo, že by to mohlo být tak jednoduché...

**Comment by zitkovalenka** [comment]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-06-Zapis_a_cteni_ze_souboru-Znamky_Bonus_CSV.py

Zde přidávám navíc bonus k tomuto úkolu (CSV formát).

**Comment by AnetaPopelova** [comment]
Super! Jsem rada, ze ti Andy pomohla :-) 

P.S.: Casto u sebe zjistuji, ze kdyz mi neco zacne pripadat moc slozite, pravdepodobne jsem nekde prehledla uplne trivialni reseni.
