### ISSUE TITLE
úkol-08: Pandas - Načtení dat

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python1-Czechitas#9]
https://github.com/zitkovalenka/Python1-Czechitas/blob/main/ukol-08_Nacteni_dat-Adopce_zvirat.ipynb

Ahoj Aneto,
odevzdávám úkol i s bonusem. Nicméně mi dělá problém kódování (viz Slack). Nyní se CSV soubor zobrazuje se správnou diakritikou (na vstup jsem použila UTF-16 LE a na výstup ANSI kódování). Nicméně při posledním příkazu na vyhledání intervalu mezi želvami, tak se mi nenajde nic. Pokud použiji interval, kde hraničními body jsou zvířata bez diakritiky, tak vše funguje správně.

**Comment by AnetaPopelova** [comment]
Ahoj,

narazila jsem na nasledujici:

- pokud to nactu s `encoding = "utf-16 LE"`, vraci mi japonske znaky. Nedari se mi zreplikovat to, co jsi popisovala (ale je to zavisle na operacnim systemu, konkretnim pocitaci...)
- kdyz t`encoding = "utf-16 LE"`, odstranim, vse se nacte v poradku

Myslim ale, ze zadrhel je jinde:
- aby jsi mohla spravne vybirat pomoci serazeneho indexu, je treba (jak tam i zminujes) prepsat tu puvodni tabulku (=dataframe, promenna) `adopce = adopce.sort_index()`. Neni treba vytvaret novy csv soubor. _Upravila jsem zadani na githubu, aby to bylo jednoznacne._ 
- pak to najde i ty zelvy - protoze to musis serazene, aby rozsah od:do fungoval spravne (v neserazene tabulce je totiz _Želva žlutočelá_ pred _Želva Smithova_...

**Comment by zitkovalenka** [comment]
Ahoj Aneto,

kód jsem upravila a už funguje. Našla jsem si i způsob, jak si seřazený soubor uložit do CSV souboru se správnou diakritikou a na něm jsem provedla vyhledání želv také. Nyní fungují oba dva způsoby. Bez kódování ANSI mi to ale vůbec nebralo.  

Stejně tak načíst soubor přímo z webu také ne. Musela jsem ho uložit do poznámkového bloku s příponou .csv a kódováním také ANSI. Vždy to pak narazilo na želvy a v některých případech i na Outloně. Takže bez tohoto bych byla při bonusu úplně nahraná.

Mám OS Windows.

**Comment by AnetaPopelova** [comment]
💯 

Mrzí mě, že ta chyba nejde zreplikovat a nemůžu ti k tomu říct víc :-( 

Poradila jsi si skvěle 👍

**Comment by zitkovalenka** [comment]
To vůbec nevadí. Hlavní bylo zjistit, že jsem to vlastně měla uložit do proměnné a ne do souboru. A už na konci jsem si říkala, že jak ten program ví, že se má vracet k tomu sesortovanému výstupu, když tam možná má uložený pořád ten původní. Ale nenapadlo mě pak už to uložit do proměnné. Resp. napadlo, ale pořád jsem to cpala do toho souboru a nepomáhalo nic.

Takže stačila rada, uložit to do proměnné a už bylo vše jasné :-)
